### PR TITLE
What would it be like without this tool

### PR DESCRIPTION
**Pull request by emtudo**

### CODE REVIEW

**Comment by gocanto** [comment]
Thanks for your interested in contributing to this project, but I am afraid I will have to reject this change since it removes the example intention.

**Comment by emtudo** [comment]
This PR simply leaves the example correctly, as it stands, if someone tries it would throw an exception.

**Comment by gocanto** [comment]
Lovely; I am reopening this :) 

Would you mind using the right exception and updating the example to abide by the updated one? 

Other than that, we are good to go. 

`Note:` You will have to rebase onto `master` to fix the given conflict.


Thanks

**Comment by emtudo** [comment]
Done!

**Comment by gocanto** [comment]
Thanks so much!

**Pull request merged**
